version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: daily_db
    volumes:
      - mongo-data:/data/db

  flask:
    build: .
    container_name: flask-container
    ports:
      - "5001:5000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: daily_db
    depends_on:
      - mongo

volumes:
  mongo-data:
